Ensure reset before lazy sync init
  Was seeing this on CI -
       NoMethodError:

       undefined method `items' for nil:NilClass

     # ./spec/wcc/contentful_spec.rb:480:in `block (4 levels) in <top (required)>'